baseURL: "https://copysheild.org"
theme: "up-business-theme"
languageCode: "en-us"

title: "CopyShield: Protect Your IP"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Copyshield"
  description: "Copyshield is an anti-piracy service provider with emphasis on using technology to counter content theft and brand infringments."
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    dribbble: "https://dribbble.com/copyshield"
    instagram: "https://www.instagram.com/copyshield/"
    facebook: "https://www.facebook.com/copyshield"
    twitter: "https://twitter.com/CopyshieldHQ"

  location:
    - "456 Main St Toronto, ON M5X 1A1 Canada"
    - "456 Main St Toronto, ON M5X 1A1 Canada"

  contact:
    - "dmca@copyshield.org"
    - "555-123-4567"

  copyright: "© 2023 Copyshield All Rights Reserved"

  postProcess: false

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2



  buttons:
    - name: "Get in touch"
      url: "mailto:dmca@copyshield.org?subject=Website89989"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#hero"
      weight: 1

    - name: "How we work"
      url: "/#"
      weight: 2




taxonomies:
  series: "series"
  tags: "tags"